/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
typedef volatile unsigned int vuint32_t;
#define RCC_BASE     0x40021000
#define PORTA        0x40010800
#define APB2ENR      *((vuint32_t*)(RCC_BASE + 0x18))
#define CRH          *((vuint32_t*)(PORTA + 0x04))
#define ODR          *((vuint32_t*)(PORTA + 0x0C))
#define IOPAEN2      2
#define GPIOA13      13
void main()
{
	APB2ENR |= (1<<IOPAEN2);
	CRH &= 0xFF0FFFFF;
	CRH |= 0x00200000;
    /* Loop forever */
	while(1){
		ODR |= (1<<GPIOA13);
		for(int i = 0 ; i<100000 ; i++);
		ODR &= ~(1<<GPIOA13);
		for(int i = 0 ; i<100000 ; i++);
	}

}
